apiVersion: v1
kind: Service
metadata:
  name: springboot-app-team2
  namespace: group1-team2
spec:
  selector:
    app: group1-team2-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30207
  type: NodePort